backend:
  name: github
  repo: michaelkaffel/ocm-website
  branch: main
  base_url: https://ocm-website-three.vercel.app
  auth_endpoint: /api/auth

media_folder: public/images/articles
public_folder: /images/articles

collections:
  - name: articles
    label: Articles
    folder: src/content/articles
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Slug, name: slug, widget: string }
      - { label: Date, name: date, widget: string }
      - { label: Category, name: category, widget: string }
      - { label: Read Time, name: readTime, widget: string }
      - { label: Description, name: description, widget: text }
      - { label: Thumbnail URL, name: thumbnail, widget: string, required: false }
      - { label: Body, name: body, widget: markdown }