import coachingHero from '../assets/coaching-hero2.png'
import usePageTitle from '../hooks/usePageTitle';

const CALENDLY_URL = 'https://calendly.com/owlmedicine/15min';

const Coaching = () => {
    usePageTitle('Coaching');

    return (
        <main className='min-h-screen bg-brand-bg text-brand-text'>
            {/* —— Hero —— */}

            <section className='relative flex min-h-screen flex-col lg:flex-row lg:items-center overflow-hiddenbg-brand-bg'>
                <div className='relative z-10 w-full px-6 pt-32 pb-8 lg:w-1/2 lg:pt-40 lg:pb-12 lg:pr-8'>
                    <h1 className='font-heading text-5xl leading-tight sm:text-6xl lg:text-7xl text-brand-accent'>
                        Trust &amp; Accountability
                    </h1>

                    <p className='mt-6 max-w-lg text-lg leading-relaxed text-brand-text/80 font-sans'>
                        Change can be hard,<br />
                        it's ok to ask for help.
                    </p>
                </div>

                <div className='mt-auto flex items-end justify-center lg:bottom-0 lg:right-0 lg:h-full lg:w-1/2 lg:justify-end'>
                    <img
                        src={coachingHero}
                        alt='Coaching with Owl Chrysalis Medicine'
                        className='h-auto w-full max-w-md lg:max-w-lg lg:h-[90%] object-contain object-bottom'
                    />
                </div>

            </section>

            {/* ── What coaching is ── */}
            <section className='px-6 py-16 md:py-20 max-w-3xl mx-auto'>
                <h2 className='font-heading text-3xl md:text-4xl text-brand-accent mb-6'>
                    What Coaching Is
                </h2>

                <p className='font-sans text-lg leading-relaxed mb-6'>
                    Most people already know what they need. They just can't make themselves do it. We fix that bit.
                </p>

            </section>

            {/* ── As a coach ── */}
            <section className='px-6 py-16 md:py-20 bg-brand-surface'>
                <div className='max-w-3xl mx-auto'>
                    {/* <h2 className='font-heading text-3xl md:text-4xl text-brand-accent mb-6'>
                        As a Coach
                    </h2>
                    <p className='font-sans text-lg leading-relaxed mb-6'>
                        Most people already know what they need to do. They just can't make themselves do it. I fix that bit.
                    </p> */}

                    <h3 className='font-heading text-2xl md:text-3xl text-brand-accent mb-4'>
                        Trauma Coaching
                    </h3>
                    <p className='font-sans text-lg leading-relaxed mb-6'>
                        Childhood experiences form the foundation of our nervous system, how we respond to stress, threats and even joy. They set the baselines for our expectations, how we give and receive love and our personalities. Some childhoods set up expectations of pain, abuse, fear and neglect everywhere we turn. We fix that too.
                    </p>

                    <h3 className='font-heading text-2xl md:text-3xl text-brand-accent mb-4'>
                        Neuroplastic Coaching
                    </h3>
                    <p className='font-sans text-lg leading-relaxed mb-2'>
                        Neuroplastic symptoms are physical sensations—most commonly chronic pain, fatigue, or tingling—generated by the brain and nervous system, rather than structural damage or tissue injury.
                    </p>
                    <p className='font-sans text-lg leading-relaxed'>
                        Neuroplastic pain occurs when neural pathways become reinforced by stress, fear, or habitual focus, effectively "learning" to produce pain. These symptoms are often reversible through neuroplastic work.
                    </p>
                </div>


            </section>

            {/* ── Common symptoms ── */}
            <section className='px-6 py-16 md:py-20 max-w-3xl mx-auto'>
                <h2 className='font-heading text-3xl md:text-4xl text-brand-accent mb-6'>
                    Common Neuroplastic Symptoms and Conditions
                </h2>

                <ul className='font-sans leading-relaxed space-y-3 mt-6 text-left ms-24 md:ms-52'>
                    <li className='font-body text-base font-semibold text-brand-text'>- Chronic Pain</li>
                    <li className='font-body text-base font-semibold text-brand-text'>- Fibromyalgia &amp; Fatigue</li>
                    <li className='font-body text-base font-semibold text-brand-text'>- Migraines</li>
                    <li className='font-body text-base font-semibold text-brand-text'>- IBS</li>
                    <li className='font-body text-base font-semibold text-brand-text'>- Vertigo &amp; Spasms</li>
                </ul>

            </section>

            {/* ── CTA ── */}
            <section className='px-6 py-20 md:py-28 text-center bg-brand-border'>
                <div className='max-w-3xl mx-auto'>
                    <h2 className='font-heading text-3xl md:text-4xl text-brand-accent mb-6'>
                        Set Up A Free Compatability Call
                    </h2>

                    <p className='font-sans text-lg leading-relaxed mb-10'>
                        See if Owl Medicine is right for you
                    </p>

                    <a
                        href={CALENDLY_URL}
                        target='_blank'
                        rel='nopener noreferrer'
                        className='inline-block bg-brand-accent text-brand-text font-heading text-xl
                                tracking-widest2 uppercase px-10 py-4 rounded
                                hover:brightness-110 transition-all duration-300'
                    >
                        Schedule Now
                    </a>
                </div>

            </section>
        </main >
    );
};
export default Coaching;